---
title: "SQL querying"
author: "Ben Baumer"
date: "2/8/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(tidyverse)
library(sds192)
library(RMySQL)
db <- dbConnect(
  MySQL(), 
  host = "scidb.smith.edu", 
  user = "sds192", 
  password = "DSismfc@S", 
  dbname = "airlines"
)
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE, 
  connection = db, 
  max.print = 20
)
```

## How to get basic information about what is in tables

```{sql, connection = db}
SELECT * FROM airports;
```


```{sql, connection = db}
SHOW TABLES;
```

```{sql, connection = db}
DESCRIBE airports;
```

```{sql, connection = db}
SELECT * FROM airports LIMIT 0, 20;
```

## Yelp dataset

```{r}
db <- dbConnect(
  MySQL(), 
  host = "scidb.smith.edu", 
  user = "sds192", 
  password = "DSismfc@S", 
  dbname = "yelp"
)
```

```{sql connection=db}
SHOW TABLES;
```

```{sql connection=db}
DESCRIBE reviews;
```

```{sql connection=db}
SELECT * FROM reviews LIMIT 0, 20;
```
```{sql connection=db}
DESCRIBE businesses;
```

```{sql connection=db, max.print=100}
SELECT 
  name AS restaurant, 
  COUNT(DISTINCT id) AS num_restaurants, 
  COUNT(*) AS num_reviews, 
  AVG(r.stars) AS avg_stars
FROM reviews AS r
JOIN businesses AS b ON r.business_id = b.id
WHERE name LIKE '%taco%'
GROUP BY id
HAVING num_reviews >= 25
ORDER BY avg_stars DESC;
```
```{sql connection=db}
SHOW PROCESSLIST;
/* KILL 17530;
```
## Explain

```{r}
db <- dbConnect(
  MySQL(), 
  host = "scidb.smith.edu", 
  user = "sds192", 
  password = "DSismfc@S", 
  dbname = "imdb"
)
```

```{sql connection=db}


SELECT * FROM title 
WHERE title LIKE '%The Hunger Games%'
  AND kind_id = 1;

#EXPLAIN
SELECT * 
FROM cast_info AS ci
JOIN title AS t ON t.id = ci.movie_id
JOIN name AS n ON n.id = ci.person_id
WHERE t.id = 4368646;

#EXPLAIN
SELECT * 
FROM cast_info AS ci
WHERE ci.movie_id = 4368646;

# Jennifer Lawrence
SELECT role, COUNT(*) AS num_movies, 
  GROUP_CONCAT(ci.movie_id) AS movies
FROM cast_info AS ci
JOIN role_type AS rt ON rt.id = ci.role_id
WHERE person_id = 3416438
GROUP BY role_id;

#EXPLAIN
SELECT role, t.production_year, COUNT(*) AS num_movies
FROM cast_info AS ci
JOIN role_type AS rt ON rt.id = ci.role_id
JOIN title AS t ON t.id = ci.movie_id
WHERE person_id = 3416438
GROUP BY ci.role_id, t.production_year
ORDER BY role_id, production_year;
```

```{sql, connection=db, output.var="jlaws"}
SELECT * FROM name WHERE name LIKE '%Lawrence, Jennifer%';
```


```{r}
jlaw <- jlaws %>%
  filter(imdb_index == "III") %>%
  pull(id)
```

### Subquery

```{sql, connection=db}
SELECT role, t.production_year, COUNT(*) AS num_movies
FROM cast_info AS ci
JOIN role_type AS rt ON rt.id = ci.role_id
JOIN title AS t ON t.id = ci.movie_id
WHERE person_id = (
    SELECT id FROM name WHERE name = 'Lawrence, Jennifer' AND imdb_index = 'III'
  )
GROUP BY ci.role_id, t.production_year
ORDER BY role_id, production_year;
```
### Join

```{sql, connection=db}
SELECT role, t.production_year, COUNT(*) AS num_movies
FROM cast_info AS ci
JOIN role_type AS rt ON rt.id = ci.role_id
JOIN title AS t ON t.id = ci.movie_id
JOIN name AS n ON n.id = ci.person_id
WHERE name = 'Lawrence, Jennifer' AND n.imdb_index = 'III'
GROUP BY ci.role_id, t.production_year
ORDER BY role_id, production_year;
```
### Binding R values into SQL

```{sql, connection=db}
SELECT role, t.production_year, COUNT(*) AS num_movies
FROM cast_info AS ci
JOIN role_type AS rt ON rt.id = ci.role_id
JOIN title AS t ON t.id = ci.movie_id
WHERE person_id = ?jlaw
GROUP BY ci.role_id, t.production_year
ORDER BY role_id, production_year;
```



## Baseball

```{r}
db <- dbConnect(
  MySQL(), 
  host = "scidb.smith.edu", 
  user = "sds192", 
  password = "DSismfc@S", 
  dbname = "lahman"
)
```


```{sql, connection=db}
SELECT 
  CONCAT(nameFirst, ' ', nameLast) AS name, 
  COUNT(DISTINCT yearID) AS num_years,
  CONCAT(MIN(yearID), '-', MAX(yearID)) AS span,
  SUM(H) AS Hits, 
  SUM(HR) AS HomeRuns,
  SUM(H) / sum(AB) AS BattingAverage
FROM Batting AS b
JOIN Master AS m ON m.playerID = b.playerID
GROUP BY b.playerID
HAVING Hits >= 3000 AND HomeRuns >= 500
ORDER BY Hits DESC;
```

