---
title: "Data wrangling"
author: "Ben Baumer"
date: "1/13/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fivethirtyeight)
```

## Some basic data wrangling

```{r}
sandy_311

# keep only some columns
sandy_nyc <- sandy_311 %>%
  select(date, contains("nyc"))

# add and/or modify a column
emergency_responders <- sandy_311 %>%
  select(date, nyc_311, nypd, fema) %>%
  mutate(
    police_and_emergency = nypd + fema,
    calls_in_thousands = nyc_311 / 1000
  )

# keep only some rows
sandy_311 %>%
  filter(date >= "2012-11-01")

sandy_311 %>%
  filter(date < "2012-11-01")

sandy_311 %>%
  filter("2012-10-25" < date | date < "2012-11-01")

# sort the data frame
sandy_311 %>%
  select(date, total, nyc_311) %>%
  arrange(nyc_311, desc(total))
```

## Aggregating

```{r}
sandy_311
library(lubridate)

sandy_311 %>%
  mutate(
    date_text = as.character(date),
    year = year(date),
    month = month(date)
  ) %>%
#  select(date, year) %>%
#  mutate(next_day = date_text + 1)
  group_by(month, year) %>%
  summarize(
    num_days = n(),
    avg_311 = mean(nyc_311),
    avg_total = mean(total), 
    begin = min(date), 
    end = max(date),
    span = paste0(begin, ":", end)
  ) %>%
  filter(num_days < 28)
```


## Babynames

```{r}
library(babynames)
babynames %>%
  filter(name == "Jackie") %>%
  group_by(year) %>%
  summarize(
    num_sexes = n(), 
    total = sum(n), 
    boys = sum(ifelse(sex == "M", n, 0)),
    girls = total - boys,
    girl_pct = girls / total
  )
```

```{r}
# approach 1: clever approach

babynames %>%
  group_by(name) %>%
  summarize(num_rows = n()) %>%
  filter(num_rows == 276)

# approach 2, more straightforward

babynames %>%
  group_by(name, sex) %>%
  summarize(
    num_rows = n()
  ) %>%
  filter(num_rows == 138) %>%
  group_by(name) %>%
  summarize(
    num_sex = n_distinct(sex)
  ) %>%
  filter(num_sex == 2)

# approach 3, similar

babynames %>%
  group_by(name, year) %>%
  summarize(num_sexes = n_distinct(sex)) %>%
  filter(num_sexes == 2) %>%
  group_by(name) %>%
  summarize(num_years = n()) %>%
  filter(num_years == 138)

```

## Joining two tables


```{r}
library(mdsr)
Violations %>%
  filter(zipcode == 11222) %>%
  select(dba, violation_code, cuisine_code)
```


```{r}
first_part <- Violations %>%
  filter(zipcode == 11222) %>%
  left_join(Cuisines, by = c("cuisine_code" = "cuisine_code"))

first_part %>%
  select(inspection_date, dba, cuisine_description, violation_code) %>%
  left_join(ViolationCodes, by = c("violation_code" = "violation_code")) %>%
  select(-critical_flag, -violation_code)
```

## Which restaurants in Greenpoint had the most violations, and what were they? 

```{r}
Violations %>%
  filter(zipcode == 11222) %>%
  group_by(dba, cuisine_code) %>%
  summarize(num_violations = n()) %>%
  arrange(desc(num_violations)) %>%
  left_join(Cuisines, by = "cuisine_code")
```

## Reading a CSV

```{r}
library(tidyverse)
life_expectancy <- read_csv("life_expectancy_years.csv")
life_expectancy <- read_csv("~/sds192-i21-scratchwork/life_expectancy_years.csv")

life_expectancy <- read_csv("bad/life_expectancy_years.csv")


```

## Joining lab, Exercise 3

What is the most commonly-used plane? Find it’s manufacturer and model.

```{r}
library(tidyverse)
library(nycflights13)

flights %>%
  inner_join(planes, by = "tailnum") %>%
  group_by(tailnum, manufacturer, model) %>%
  summarize(num_flights = n()) %>%
  arrange(desc(num_flights))

flights %>%
  group_by(tailnum) %>%
  summarize(num_flights = n()) %>%
  arrange(desc(num_flights)) %>%
  inner_join(planes, by = "tailnum")

flights %>%
  group_by(tailnum) %>%
  summarize(num_flights = n()) %>%
  arrange(desc(num_flights)) %>%
  left_join(planes, by = "tailnum")
```

```{r}
flights %>%
  left_join(planes, by = "tailnum") %>%
  group_by(model) %>%
  summarize(num_flights = n()) %>%
  arrange(desc(num_flights))
```

## Pivoting

```{r}
library(fivethirtyeight)
ggplot(data = drug_use, aes(x = age, y = alcohol_use)) +
  geom_point()


drug_use %>%
  select(age, alcohol_use, marijuana_use, cocaine_use) %>%
  pivot_longer(-age, names_to = "substance", values_to = "usage_rate") %>%
  ggplot(aes(x = age, y = usage_rate, color = reorder(substance, usage_rate))) +
  geom_point()
```

## FEC


```{r}
library(fec16)

contributions %>% View()

one_trans <- contributions %>%
  head(3)
one_trans %>%
  select(cmte_id, entity_tp, name, other_id, cand_id)

committees %>%
  filter(cmte_id == "C00002766") %>%
  select(cmte_id, cmte_nm, cand_id)

committees %>%
  filter(cmte_id == "C00433136") %>%
  select(cmte_id, cmte_nm, cand_id)

candidates %>%
  filter(cand_id == "S6NC00266") %>%
  select(cand_id, cand_name)

one_trans %>%
  left_join(committees, by = c("cmte_id" = "cmte_id")) %>%
  left_join(committees, by = c("other_id" = "cmte_id")) %>%
  left_join(candidates, by = c("cand_id" = "cand_id")) %>%
  select(
    spender = cmte_nm.x, 
    recipient = name, 
    recipient2 = cmte_nm.y, 
    cand_name
  )

```


```{r}
contributions %>%
  group_by(transaction_tp) %>%
  summarize(
    num_transactions = n(),
    total_amount = sum(transaction_amt)
  )

contributions %>%
  filter(transaction_amt < 0) %>% View()

contributions %>%
  filter(cmte_id == "C00242040")
```


## Reading data

```{r, eval=FALSE}
contributions_all <- read_all_contributions()
saveRDS(contributions_all, "contributions_all.rda")

transactions_all <- read_all_transactions()
saveRDS(transactions_all, "transactions_all.rda")

expenditures_all <- read_all_expenditures()
saveRDS(expenditures_all, "expenditures_all.rda")

# watch out this could take a looooong time!
individuals_all <- read_all_individuals()
saveRDS(individuals_all, "individuals_all.rda")
```

```{r}
contributions_all <- readRDS("contributions_all.rda")
```

## Reconciliation

```{r}
# food workers
food_contributions <- contributions_all %>%
  filter(cmte_id == "C00002766")

food_transactions <- transactions_all %>%
  filter(cmte_id == "C00002766")

food_expenditures <- expenditures_all %>%
  filter(cmte_id == "C00002766")

food_contributions %>%
  inner_join(food_transactions, by = "tran_id")

food_expenditures %>%
  inner_join(food_transactions, by = "tran_id")

food_transactions %>%
  anti_join(food_contributions, by = "tran_id") %>% View()
```

```{r}
# Working America
working_contributions <- contributions_all %>%
  filter(cmte_id == "C90011156")

working_transactions <- transactions_all %>%
  filter(cmte_id == "C90011156")

working_expenditures <- expenditures_all %>%
  filter(cmte_id == "C90011156")

working_contributions %>%
  left_join(working_transactions, by = "tran_id")

length(unique(working_contributions$tran_id))
length(unique(working_transactions$tran_id))

# Working-Brewer

brewer_contr <- working_contributions %>%
  filter(name == "BREWER, SANDRA") %>%
  left_join(candidates, by = c("cand_id")) 

working_contributions %>%
  filter(transaction_tp != "24A")

brewer_trans <- working_transactions %>%
  filter(name == "BREWER, SANDRA")

brewer_contr %>%
  inner_join(brewer_trans, by = "tran_id") %>% View()

brewer_contr %>%
  filter(tran_id == "VN7CZA3SHB5")

brewer_trans %>%
  filter(tran_id == "VN7CZA3SHB5")

candidates %>%
  filter(cand_id == "S4NC00089")
```

## Report types

```{r}
contributions_all %>%
  group_by(rpt_tp) %>%
  summarize(
    num_contributions = n(),
    num_transactions = n_distinct(tran_id),
    total_amount = sum(transaction_amt)
  ) %>%
  arrange(desc(total_amount))

working_contributions %>%
  group_by(rpt_tp) %>%
  summarize(
    num_contributions = n(),
    total_amount = sum(transaction_amt)
  ) %>%
  arrange(desc(total_amount))
```

## Entity types

```{r}
transactions_all %>%
  group_by(entity_tp) %>%
  summarize(
    num_contributions = n(),
    total_amount = sum(transaction_amt)
  ) %>%
  arrange(desc(total_amount))

contributions_all %>%
  group_by(entity_tp) %>%
  summarize(
    num_contributions = n(),
    total_amount = sum(transaction_amt)
  ) %>%
  arrange(desc(total_amount))
```

