---
title: "Programming with data"
author: "Ben Baumer"
date: "1/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Functions

```{r}
starwars

ggplot(starwars, aes(x = mass, y = height)) + 
  geom_point() + 
  facet_wrap(~species)
```

### Isolates a certain species and draws a plot

```{r}
plot_species <- function(species_arg = "Human", highlight_color) {
  starwars %>%
    filter(species == species_arg) %>%
    ggplot(aes(x = mass, y = height)) + 
    geom_point(color = highlight_color)
}
```

```{r}
# works
plot_species("Droid", "red")

# no error, no data
plot_species("red", "Droid")

# works
plot_species("red", species_arg = "Droid")

# works
plot_species(highlight_color = "red", "Droid")

# works, default value for species_arg
plot_species(highlight_color = "red")

formals("plot_species")
```


### Global vs. local variables

```{r}
plot_species2 <- function(species_arg = "Human", highlight_color) {
  # starwars is available locally, but not *defined* locally!
  species_data <- starwars %>%
    filter(species == species_arg)
  ggplot(species_data, aes(x = mass, y = height)) + 
    geom_point(color = highlight_color)
}
```

```{r}
plot_species2(highlight_color = "blue")

# local variable not in Global environment
species_data

find("starwars")
search()


starwars <- "nothing"

plot_species2(highlight_color = "blue")
```

## Iteration

```{r}
library(tidyverse)

starwars %>%
  group_by(species, sex) %>%
  select(height, mass) %>%
  summarise(
    height = mean(height, na.rm = TRUE),
    mass = mean(mass, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = height, y = mass)) +
  geom_point()
```

### Vectorized functions

```{r}
c(1, 4, 7)^2
exp(c(1:10))

nchar(c("word", "another", "thing"))
```

### Loops

```{r}
# you can for loops in R, but don't!
for (i in 1:10) {
  print(i)
}

map(1:10, print)

# base R pattern -- use map() instead
lapply(1:10, print)

# map always returns a list
map(1:10, exp) %>% class()

# map_dbl always returns a double
map_dbl(1:10, exp) %>% class()

# probably useless
map_chr(1:10, exp)

```


```{r}
library(babynames)
most_popular_year <- function(name_arg) {
  babynames %>%
    filter(name == name_arg) %>%
#    filter(name %in% name_arg) %>%
#    filter(name == name_arg1 | name == name_arg2) %>%
    group_by(year) %>%
    summarize(total = sum(prop)) %>%
    arrange(desc(total)) %>%
    head(1) %>%
    select(year)
}

# doesn't work because most_popular_year is NOT vectorized!
most_popular_year(c("Benjamin", "Cory"))
# doesn't work because function only takes on argument
most_popular_year("Benjamin", "Cory")

# give me *one* data frame
map_dfr(c("Benjamin", "Cory"), most_popular_year)
# equivalent
c("Benjamin", "Cory") %>%
  map(most_popular_year) %>%
  bind_rows()
```

## Multiple arguments

```{r}
most_popular_year <- function(name_arg, n = 1) {
  babynames %>%
    filter(name == name_arg) %>%
    group_by(name, year) %>%
    summarize(total = sum(prop)) %>%
    arrange(desc(total)) %>%
    head(n) %>%
    select(year)
}

# 10 most popular years
most_popular_year("Benjamin", n = 10)

c("Benjamin", "Cory") %>%
  map_dfr(most_popular_year, n = 5)

# same! But less efficient coding-wise (more typing)
bind_rows(
  most_popular_year("Benjamin", n = 5),
  most_popular_year("Cory", n = 5)
)

bind_rows(
  most_popular_year("Benjamin", n = 5),
  most_popular_year("Cory", n = 3)
)

# doesn't really do what we want -- doesn't iterate over n
c("Benjamin", "Cory") %>%
  map_dfr(most_popular_year, n = c(3, 5))

map2_dfr(c("Benjamin", "Cory"), c(3, 5), most_popular_year)

c("Benjamin", "Cory") %>%
  map2_dfr(c(3, 5), most_popular_year)

```

## Using the formula interface

```{r}
names <- c("Benjamin", "Cory")

# same as above, but using formula interface
names %>%
#  map_dfr(most_popular_year)
  map_dfr(~most_popular_year(.x))


names %>%
#  map2_dfr(c(3, 5), most_popular_year)
  # alternatively...
  map2_dfr(c(3, 5), ~most_popular_year(.x, .y))

```

```{r}
top10 <- function(data) {
  data %>%
    group_by(name) %>%
    summarize(births = sum(n)) %>%
    arrange(desc(births)) %>%
    head(10)
}
top10(data = babynames)


top_by_decade <- babynames %>%
  mutate(decade = 10 * floor(year / 10)) %>%
  group_by(decade) %>%
  group_modify(~top10(.x))

# pseudocode!!
top10(filter(babynames, decade == "1880s"))
top10(filter(babynames, decade == "1890s"))


babynames %>%
  mutate(decade = 10 * floor(year / 10)) %>%
  group_by(decade) %>%
  group_modify(~top10(.x))
```

## Assignment

```{r}
starwars <- "nothing"

# same!
starwars = "nothing"

# other direction
starwars -> nothing
```

```{r}
# ask a question?
starwars == "nothing"

starwars %>%
  filter(species == "Human")

starwars %>%
  mutate(are_you_tall = height > mass) %>%
  filter(!are_you_tall)

# works, because 1 divides 87
starwars %>%
  filter(TRUE)

# doesn't work, because 2 doesn't divide 87
starwars %>%
  filter(c(TRUE, FALSE))


starwars %>%
  filter(species == "Human")

# fails, but...
starwars %>%
  filter(species == Human)

# works if there is a variable in starwars called "Human"
starwars %>%
  mutate(Human = rep(c("Human", "Droid", "Wookiee"), 29)) %>%
  filter(species == Human)

# also works if Human exists in global environment, and is appropriately sized!
# works, because it's of lenght 87
Human <- rep(c("Human", "Droid", "Wookiee"), 29)
# doesn't work, because not of length 87
Human <- rep(c("Human", "Droid", "Wookiee"), 25)
starwars %>%
  filter(species == Human)


```

## Factors


```{r}
starwars %>%
  glimpse()

# tidyverse equivalence
hair <- starwars %>%
  pull(hair_color)

# base R pattern to extract a vector from a data.frame
starwars$hair_color

class(hair)

fct_hair <- factor(hair)

# factors can be converted to integers!
as.integer(fct_hair)

# character vectors cannot be converted to integers!
as.integer(hair)
```

### Ordering

```{r}
levels(fct_hair)
is.ordered(fct_hair)

# facets appear in order of default levels of hair_color
ggplot(starwars, aes(x = mass, y = height)) + 
  geom_point() +
  facet_wrap(~hair_color)


# change the order of the factor levels
starwars_inorder <- starwars %>%
  mutate(
    fct_hair = factor(hair_color, ordered = TRUE),
    fct_hair2 = fct_reorder(fct_hair, birth_year)
  )

starwars_inorder %>%
  pull(fct_hair) %>%
  levels()

starwars_inorder %>%
  pull(fct_hair2) %>%
  levels()

ggplot(starwars_inorder, aes(x = mass, y = height)) + 
  geom_point() +
  facet_wrap(~fct_hair2)

factor(c("1", "10", "2"), levels = c("1", "2", "10"), ordered = TRUE)

factor(c("1", "10", "2"), levels = c("1", "2", "10"), ordered = TRUE) %>% sort()

fct_reorder(factor(c("1", "10", "2"), ordered = TRUE), c("1", "2", "10"))
```

