---
title: "Geospatial data"
author: "Ben Baumer"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(macleish)
```

## Basic data exploration

```{r}
boundary <- macleish_layers %>%
  pluck("boundary")

trails <- macleish_layers %>%
  pluck("trails")

trails %>%
  filter(name == "Western Loop")
```

## Static plots

```{r}
ggplot(boundary) +
  geom_sf() + 
  geom_sf(data = trails, aes(color = name)) +
  scale_color_brewer(palette = "Set2")
```

## Dynamic plots

```{r}
library(leaflet)
leaflet(boundary) %>%
  addTiles() %>%
  addPolygons() %>%
  addPolylines(data = trails)
```

## Working with lists

```{r}
str(macleish_layers)

# fine -- it's a base R pattern -- not pipeable
macleish_layers$boundary

# works, but returns a *list* and it also not pipeable!
macleish_layers["boundary"]

# same as $ or pluck() pattern -- returns an `sf` object -- not pipeable
macleish_layers[["boundary"]]

# returns an `sf` object and is pipeable!
macleish_layers %>%
  pluck("boundary")
```

## Bike trails

```{r}
url <- "http://download.massgis.digital.mass.gov/shapefiles/state/biketrails_arc.zip"
local_file <- basename(url)
download.file(url, destfile = local_file)
unzip(local_file, exdir = "biketrails")
```

```{r}
library(sf)
# no longer necessary
# path.expand("~/sds192-i21-scratchwork/biketrails/biketrails_arc/")
bike_trails <- read_sf("biketrails/biketrails_arc")
bike_trails
```

- `st_*()` functions

```{r}
trail_lengths <- bike_trails %>%
  select(TRAILNAME, SHAPE_LEN) %>%
  mutate(trail_length = st_length(geometry))

trail_lengths %>%
  pull(trail_length) %>%
  units::set_units("miles")
```


- units
- pronouns

```{r}
library(leaflet)

bike_trails_4326 <- bike_trails %>%
  st_transform(4326)

leaflet(bike_trails_4326) %>%
  addTiles() %>%
  addPolylines(popup = ~TRAILNAME) %>%
  addPolygons(data = pluck(macleish_layers, "boundary"), popup = ~Shape_Leng)


ggplot(bike_trails) + 
  geom_sf(aes(color = TRAILNAME))
```

- `~` (in `leaflet` and in general)

```{r}

leaflet(pluck(macleish_layers, "boundary")) %>%
  addTiles() %>%
  addPolylines(data = bike_trails_4326, popup = ~TRAILNAME) %>%
  addPolygons(popup = ~Shape_Leng)


leaflet() %>%
  addTiles() %>%
  addPolylines(data = bike_trails_4326, popup = ~TRAILNAME) %>%
  addPolygons(data = pluck(macleish_layers, "boundary"), popup = ~Shape_Leng)
```

## Color in leaflet

```{r}
# doesn't work
leaflet(pluck(macleish_layers, "boundary")) %>%
  addTiles() %>%
  addPolylines(data = bike_trails_4326, popup = ~TRAILNAME, color = ~TRAILNAME)
```

## Areas

```{r}
forests <- macleish_layers %>%
  pluck("forests")

# approach 1 -- computing areas of each of 54 features, and then adding them up
forests %>%
  mutate(forest_area = st_area(geometry)) %>%
  group_by(type) %>%
  summarize(
    total_area = sum(forest_area),
    total_area_acres = units::set_units(total_area, "acres"),
    total_area_acres2 = total_area / 4356
  )

# also works
forests %>%
  group_by(type) %>%
  summarize(
    total_area = sum(st_area(geometry))
  )

# approach 2 -- spatial aggregation and then area computation of 16 features
forests %>%
  group_by(type) %>%
  summarize(num_forests = n(), do_union = FALSE) %>%
  mutate(total_area = st_area(geometry))
```

## Joins and spatial joins

```{r}
camp_sites <- macleish_layers %>%
  pluck("camp_sites")

camp_sites

camp_attributes <- tibble(
  name = c("Group Campsite", "Remote Campsite"),
  capacity = c(6, 3),
  has_firewood = c(TRUE, FALSE)
)

# same thing!
camp_attributes <- tribble(
  ~name, ~capacity, ~has_firewood, 
  "Group Campsite", 6, TRUE,
  "Remote Campsite", 3, FALSE
)

# non-spatial join -- uses left_join.sf() method
camp_sites_extra <- camp_sites %>%
  left_join(camp_attributes, by = "name")

library(leaflet)

leaflet(camp_sites_extra) %>%
  addTiles() %>%
  addMarkers(popup = ~paste("<b>", name, "</b><br>", capacity))
```


```{r}
# left join
camps_forests <- camp_sites_extra %>%
  st_join(forests)

# inner_join -- POINT geometry
camp_sites_extra %>%
  st_join(forests, left = FALSE)

# left join -- equivalent to right join of original use of st_join()
forests %>%
  st_join(camp_sites_extra)

# MULTIPOLYGON geometry!!
forests_intersecting_camps <- forests %>%
  st_join(camp_sites_extra, left = FALSE)

# returns nothing because forests are not covered by camp sites
forests %>%
  st_join(camp_sites_extra, left = FALSE, join = st_covered_by)



leaflet(camps_forests) %>%
  addTiles() %>%
  addMarkers(popup = ~paste("<b>", name, "</b><br>", capacity)) %>%
  addPolygons(data = forests_intersecting_camps, popup = ~type)
```

